### ISSUE TITLE
Please how do I make my site look like somerandomdude.com

### ISSUE THREAD

**Issue by komputa** [arnabwahid/Frank#149]
Thank you greatly for this job.

Please how do I make my website https://jekayode.com/ look exactly like the http://somerandomdude.com/ with the "big" title, sidebar profile and reduced home content.

Thanks

**Comment by komputa** [comment]
Updating menu doesnt go to the right side as it is on http://somerandomdude.com/. Also, I couldnt get to be able to make it display read on stuff.

**Comment by komputa** [comment]
Finally, I get it right!

I just downloaded the child theme, installed it and with little customization, I am home dry.

https://jekayode.com/ is now like I wanted it be

Thanks for the great  job

**Comment by aaronduce** [comment]
Hi mate, dont know if you will read this but where do you get the child theme?
