### ISSUE TITLE
Is the theme still in development?

### ISSUE THREAD

**Issue by pixeldetective** [arnabwahid/Frank#150]
I see that the last release was in mid-2013, close to two years back. Before I start using it, I wanted to know if Frank is being actively developed and would be getting future releases or bug fixes.

**Comment by parasdahal** [comment]
I'm interested in contributing if it's still being maintained.

**Comment by borisov87** [comment]
There i see author saw not going to be able to work on this project. 
https://github.com/somerandomdude/Frank/issues/142
 somerandomdude commented on Jul 18, 2014

I'm not going to be able to work on this project in the near future and would love to hand it over to anyone interested. Message me if you know anyone interested.

**Comment by 0x10c** [comment]
Hello.
Someone continues project? Or have been abandoned?
