### ISSUE TITLE
Some Good News!

### ISSUE THREAD

**Issue by arnabwahid** [arnabwahid/Frank#156]
A major rewrite from scratch is underway! As of now, no a single line of code from this stale branch will make it to the new one. 
After prolonged discussions, we have decided to this the proper way. Not only v2 will be cleverly crafted for speed, it will also going to be live in official WordPress theme depository very soon. I am a bit short handed doing all these on my own, so any one willing to contribute in the development are very welcome. `PRs` are welcome.
Frank lovers, please be patient, It is coming back within a couple of months!

**Comment by prhomhyse** [comment]
Definitely, I am willing to contribute. 
Is there an active branch for the development yet?
